<?php

use Tracy\Dumper;

/**
 * @var \Holabs\Logger\Log[] $logs
 * @var int $count
 * @var string $name
 * @var string $storage
 */

?>

<style>
	#tracy-debug .holabs-logger-label{font-weight: bold;}
	#tracy-debug .holabs-logger-table{width: 100%;}
	#tracy-debug .holabs-logger-inner{margin-top: 20px;}
</style>

<h1>Logger</h1>
<?php if ($count): ?> <span class="holabs-logger-label">Count:</span> <?php echo $count; ?><br> <?php endif; ?>
<span class="holabs-logger-label">Logger:</span> <?php echo $name; ?><br>
<span class="holabs-logger-label">Storage:</span> <?php echo $storage; ?><br>

<div class="nette-inner holabs-logger-inner">
	<table class="holabs-logger-table">
		<tr><th>Time</th><th>Type</th><th style="min-width: 150px">Parameters</th><th>IP</th></tr>
		<?php foreach ( $logs as $log ): ?>
			<tr>
				<td><?php echo $log->getTime()->format('H:i:s'); ?></td>
				<td><?php echo $log->getAction(); ?></td>
				<td><?php echo Dumper::toHtml($log->getParams()); ?></td>
				<td><?php echo $log->getIp(); ?></td>
			</tr>
		<?php endforeach; ?>
	</table>
</div>
